rules = {
    "Saprolegniasis": {"sirip_benang_halus", "insang_benang_halus", "kulit_cerah"},
    "Aeromoniasis": {"luka_merah", "sirip_rusak", "berenang_tidak_normal"},
    "Dropsy": {"perut_bengkak", "sisik_mengembang"},
    "Columnaris": {"sirip_rusak", "bercak_putih", "luka_merah"},
    "Kutu": {"sirip_bercak_merah", "kulit_gelap", "kulit_pucat", "kulit_luka"},
    "Myxosporeasis": {"insang_benjolan", "insang_luka", "kulit_gelap", "kulit_luka", "produksi_lendir_berlebih"},
    "Bintik Putih": {"sirip_luka", "insang_luka", "kulit_bintik_putih", "kulit_cerah"},
    "Lerneasis": {"sirip_luka", "insang_luka", "kulit_gelap", "kulit_pucat", "produksi_lendir_berlebih", "kulit_benang_halus", "mata_luka"},
    "Velvet Disease": {"lapisan_tipis_keemasan", "pernapasan_cepat", "produksi_lendir_berlebih", "perilaku_menggosok_tubuh"},
    "Vibrio Infection": {"nafsu_makan_menurun", "kulit_gelap", "kulit_luka"},
    "Sleepy Grouper Disease": {"nafsu_makan_menurun", "mengapung_di_permukaan", "kulit_gelap"},
    "Viral Nervous Necrosis": {"nafsu_makan_menurun", "berenang_melingkar", "kehilangan_keseimbangan"},
    "Popeye": {"mata_membesar", "mata_menonjol", "mata_keruh"},
    "Trichodiniasis": {"iritasi_kulit", "produksi_lendir_berlebih", "insang_pucat", "nafsu_makan_menurun", "sirip_ekor_rusak", "sirip_bercak_merah"},
    "Argulosis": {"sirip_bercak_merah", "luka_merah", "perilaku_menggosok_tubuh", "nafsu_makan_menurun", "ikan_di_dasar_perairan", "sirip_luka"},
    "Benedeniasis": {"iritasi_kulit", "produksi_lendir_berlebih", "kulit_luka", "sirip_rusak", "kesulitan_bernapas"},
    "Cryptocaryoniasis": {"kulit_bintik_putih", "perilaku_menggosok_tubuh", "kesulitan_bernapas", "nafsu_makan_menurun"},
    "Amyloodiniosis": {"lapisan_tipis_keemasan", "produksi_lendir_berlebih", "kesulitan_bernapas", "perilaku_menggosok_tubuh"},
    "Tuberculosis": {"kulit_gelap", "perut_kembung", "organ_dalam_bintik"},
    "Pseudomonas": {"sirip_rusak", "sirip_bercak_merah", "sirip_luka", "kulit_gelap", "kulit_luka", "perut_kembung", "mata_menonjol"},
    "Hervesvirus": {"sirip_luka", "kulit_pucat", "produksi_lendir_berlebih", "mata_menonjol", "organ_dalam_luka"}
}